### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by KubaSzostak** [NetTopologySuite/NetTopologySuite.IO.Esri#1]
Before I get started I would like clarify [proposed repository structure](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/issues/81#issuecomment-1077562642).

1. My <https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/pull/69> pull request introduced two new VS projects: _NetTopologySuite.IO.Esri.Core_ and _NetTopologySuite.IO.Esri_. The former provides shapefile readers and writers as vanilla .NET Standard 2.0 library without any dependencies.  The latter is a wrapper around _Core_ project which gives NTS geometries instead of bunch of collections of coordinates.  This separation causes some issues. For example coordinates are first loaded into plain `Array` and then copied to NTS' `CoordinateSequence`. It would be more efficient to load them directly from binary into `CoordinateSequence`. Furthermore the _Core_ project doesn't contain any geometry logic (line length, polygon area, ...). Because of that some issues will be very hard to fix directly in _Core_ project. For example fixing <https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/issues/70> will be much easier having NTS' `LinearRing.IsCCW` property. For that reasons I would like to combine those two projects into one project which is tightly integrated with NTS library.
2. We can consider moving dBASE part into separate project without NTS dependencies. After doing so one would be able to read/write dBASE tables without referencing NTS dependencies. As my implementation uses "Esri flavored" dBASE format it fits to this repository very well.
3. I'm not a fan of maintaining _NetTopologySuite.IO.GDB_ anymore
    - I'm not sure (and probably any new consumer of the library won't be) which GDB is actually implemented 
        - [Enterprise GDB](https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/sql-access-to-geodatabase-data.htm), 
        - [File GDB](https://github.com/Esri/file-geodatabase-api), 
        - [Workgroup GDB](https://enterprise.arcgis.com/en/server/10.8/manage-data/windows/workgroup-geodatabases.htm) 
        - [Personal GDB](https://desktop.arcgis.com/en/arcmap/latest/manage-data/administer-file-gdbs/personal-geodatabases.htm)
    - Almost certainly it It can't be _File GDB_. It rather isn't _Enterprise GDB_ because it supports a lot of [geometry storage options](https://desktop.arcgis.com/en/arcmap/latest/manage-data/geodatabases/configuration-keywords-for-enterprise-geodatabases.htm) and here we have only one implementation. So it could be _Workgroup GDB_ or _Personal GDB_. Both of tehm are supported only by ArcMap which was [retired in 2020](https://www.esri.com/arcgis-blog/products/arcgis-desktop/announcements/arcmap-continued-support/). 
    - [Esri recommends migrating](https://support.esri.com/en/technical-article/000022791) existing data using Esri Binary type.
    -  I'm not able to test it.
4. Project naming convention - shouldn't the project names correspond strictly to _NetTopologySuite.IO.Esri_?
    - NetTopologySuite.IO.**Esri**.Shapefile
    - NetTopologySuite.IO.**Esri**.GDB
    - [NetTopologySuite.IO.**Esri**.Dbase]
    - [NetTopologySuite.IO.**Esri**.EnterpriseGeodatabase]

What do you think, @FObermaier?

**Comment by airbreather** [comment]
> For example coordinates are first loaded into plain `Array` and then copied to NTS' `CoordinateSequence`. It would be more efficient to load them directly from binary into `CoordinateSequence`.

If this were the only concern, then perhaps you could give [`RawCoordinateSequenceFactory`](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Implementation.RawCoordinateSequenceFactory.html) a try?  [`CommunityToolkit.HighPerformance`](https://www.nuget.org/packages/CommunityToolkit.HighPerformance) includes some helpers that should let you reinterpret any `Memory<byte>` as a `Memory<double>`, then you could create a `CoordinateSequence` wrapping it.

I expect a little bit of a performance penalty compared to some other sequence types when the `Geometry` is actually used, but it may well be worth it to avoid full copies...

**Comment by KubaSzostak** [comment]
Thank you @airbreather for your comment. Storing coordinates in efficient way is a big concern for me to. I'm not familiar with all different types of geometry factories, so I was going to require `GeometryFactory` in the constructor and use `NtsGeometryServices.Instance.CreateGeometryFactory()` if null provided. 
```c#

public ShpStreamBase(ShapeType shapeType, GeometryFactory factory)
{
    ...  
    Factory = factory ?? NtsGeometryServices.Instance.CreateGeometryFactory();
    ...  
}

internal CoordinateSequence GetCoordinateSequence(int size)
{
    return Factory.CoordinateSequenceFactory.Create(...);
}
```
You mean I should always use `RawCoordinateSequenceFactory`? In my project I have referenced NetTopologySuite 2.0.0 and `RawCoordinateSequenceFactory` isn't visible within `NetTopologySuite.Geometries.Implementation` namespace. Should I upgrade NTS version? To which one?

**Comment by FObermaier** [comment]
A few notes:
* I have no issue with merging NetTopologySuite.IO.Esri.Core in NetTopologySuite.IO.Esri.Shapefile
* `RawCoordinateSequence[Factory]` comes with NTS v2.3 (https://github.com/NetTopologySuite/NetTopologySuite/issues/482). The flatgeobuf c# implementation uses its own, specialized [CoordinateSequence/CoordinateSequenceFactory](https://github.com/flatgeobuf/flatgeobuf/tree/master/src/net/FlatGeobuf/NTS) pair. I'm not sure if that is an option here, too.
* I support the naming convention proposed.
* If it is not clear which kind of GDB is format is meant, we should not add it to this new project.
  If there are complaints, we can add it afterwards.

**Comment by DGuidi** [comment]
> I'm not sure (and probably any new consumer of the library won't be) which GDB is actually implemented

Looking at the docs it "Writes features as ESRI GeoDatabase **binary format** in a SqlServer database", looking at the [code](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/develop/src/NetTopologySuite.IO.GDB/GDBWriter.cs) it simply extends snts.io.shp `ShapeReader/Writer` and adds almost nothing.

So I can assume that ESRI binary format is exactly the shapefile geometry format, stored in a sql column. +1 to leave this code in the deprecated library, at least for now.

**Comment by FObermaier** [comment]
@kubaszostak if you are already working on this topic I encourage you to let us take part in the process.

**Comment by KubaSzostak** [comment]
I have started working on merging and cleaning up the projects at the weekend. I will push the code within the next few days.

**Comment by KubaSzostak** [comment]
[Initial commit](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/commit/1bfc994ea33a4f07834a5427881c4d0a02099ec3)

**Comment by FObermaier** [comment]
Thanks @kubaszostak !

**Comment by kristofdegrave** [comment]
Can you please provide solutions using streams instead of only focusing on files?
Our use-cases needs to work in the cloud, so using filepaths won't be possible.
