### ISSUE TITLE
DBF * in numeric field

### ISSUE THREAD

**Issue by MattPil29** [NetTopologySuite/NetTopologySuite.IO.Esri#11]
Hi,
I was passed a simple shp file made by QGIS.  It errors out on reading in.  A quick debug finds a string of * in the numeric ID field.  We added the following quick fix: 

![readval](https://user-images.githubusercontent.com/2870919/205634550-2f7ad0b2-25e4-47c5-a3d4-282f2f24dfac.PNG)

I wonder if you have a better approach that could be folded in to the repo?  File attached.
[WallaceMonument.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/files/10154052/WallaceMonument.zip)

PS is there a nuget for this repo? couldn't locate it on last look.

thanks in advance, and cheers for the work, Matt

**Comment by KubaSzostak** [comment]
> A quick debug finds a string of * in the numeric ID field.

Numeric field should have numeric value... What does '*' mean in this case? 

> PS is there a nuget for this repo?

No nuget package yet. For news on this topic monitor #3.

**Comment by MattPil29** [comment]
Thanks for quick response.  I agree you'd expect a number in a number field.   The user didn't do anything on purpose, I belive the Id is NULL in QGIS.  I have seen this in another file also.  

I thought you may have experienced this.  DBASE refers to * as a deleted marker.  Not sure if thats releveant though.

Either way this was a legitimate end user file that crashed out so maybe my quick fix is useful!

**Comment by KubaSzostak** [comment]
Deleted marker (`*`) should precede all record values. It shouldn't be placed in field bytes. Nevertheles, in free time I will check the DBF.

Could you provide the steps to reproduce such DBF using QGIS?

**Comment by MattPil29** [comment]
happy to. have someone working on it now.

**Comment by MattPil29** [comment]
[QGIS_adding_shapefiles.pdf](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/files/10154689/QGIS_adding_shapefiles.pdf)

Key step is on page 3 in yellow highlight.

**Comment by KubaSzostak** [comment]
Thank you @MattPil29 for valuable insights.
