### ISSUE TITLE
Export shape file with (spatial reference) WKT 

### ISSUE THREAD

**Issue by hbadry** [NetTopologySuite/NetTopologySuite.IO.Esri#16]
Hi. 
thank you guys for this library. 
I am inexperienced with shape files but I want to export shapefile with it's WKT, when I do export shape file by using the library 
with the following code.
```cs
       List<Feature> features = new List<Feature>();
       var geoReader = new GeoJsonReader();
       var feature = geoReader.Read<Feature>(jsonData);
       List<Feature> features = new List<Feature>(){feature};
       Shapefile.WriteAllFeatures(features, "C:\\Logs\\test.shp");
```
it works fine and I got the following files 
`test.dbf`
`test.shp`
`test.shx`
`test.cpg`
but when I try to add these shape file to tool like ArcGIS Pro, I got the following warning 
![image](https://user-images.githubusercontent.com/66202294/209976140-f2008ad4-0b81-486f-80c0-537cc15b9d9d.png)
What I need to do is to export WKT files with the shapefile.
I except files like  `test.prj` which holds the projects coordinate system
Thanks

**Comment by kronetix** [comment]
Issue

Regards,
Dan

**Comment by kronetix** [comment]
Output must pass 3rd party implementation

Regards,
Dan

**Comment by hbadry** [comment]
Dear @kronetix 
What I need to do is to export WKT files for the shape file
Regards,

**Comment by KubaSzostak** [comment]
Good point. The `Shapefile.WriteAllFeatures()` method does not have an option to specify the projection. For now you have to use `ShapefileWriter` with explictly specified options:

```cs
var geoReader = new GeoJsonReader();
var features = geoReader.Read<FeatureCollection>(GeoJsonData);

var prop0 = new DbfCharacterField("prop0");
var prop1 = new DbfCharacterField("prop1");
var options = new ShapefileWriterOptions(ShapeType.Polygon, prop0, prop1)
{
    Projection = @"GEOGCS[""GCS_WGS_1984"",DATUM[""D_WGS_1984"",SPHEROID[""WGS_1984"",6378137.0,298.257223563]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]]"
};

var shpPath = "C:\\Temp\\Issue016.shp";
using (var shpWriter = Shapefile.OpenWrite(shpPath, options))
{
    shpWriter.Write(features);
}
```

**Comment by hbadry** [comment]
Thanks @KubaSzostak, this is a great solution.
