### ISSUE TITLE
Reprojection

### ISSUE THREAD

**Issue by sarteleb** [NetTopologySuite/NetTopologySuite.IO.Esri#22]
Is there any way to reproject the geometries to a new coordinate system once they've been read in from the shape file?  This reader doesn't seem to take into account the .prj file.  Do I need to use an additional nuget package?

**Comment by macias** [comment]
@sarteleb So what is the solution? :-) I am asking because I have exactly this problem (or more exactly two -- how to get info about projection/coordinate system used, and then how to project it to latitude+longitude).
