### ISSUE TITLE
Multi-polygon bringing in extra/redundant polygons?

### ISSUE THREAD

**Issue by Em3a-c** [NetTopologySuite/NetTopologySuite.IO.Esri#26]
Hi all,

I've been testing out reading in shapefiles with your library, to look at replacing another library that we currently use that doesn't handle text encoding very well (https://github.com/abfo/shapefile).

However, I've noticed that reading in multi-polygon shapefiles with your library, in a few examples, seems(?) to read in unexpected polygons.

I don't think I've described the issue very well, but below I've got 2 screen shots, rendering the shapefile in question, using the Microsoft Bing Map control, which hopefully showcases what I'm describing.

The first image is from the other shapefile library
![OGA_Geological_Sub_WGS84_expected](https://user-images.githubusercontent.com/60915240/224982650-95ab8bfa-33f2-4783-9403-61e8a9cb2a40.PNG)

The 2nd image is from your library, which has some additional polygons being read in and rendered.
![OGA_Geological_Sub_WGS84_Esri_lib](https://user-images.githubusercontent.com/60915240/224982742-cf667776-0fae-4270-83ce-cfa11558c939.PNG)

I'm not overly familiar with shapefiles, so this may not be an issue with your library, but maybe with the shapefile itself(?), or it could be something that we need to handle ourselves, after we've read in the shapefiles?
I thought I would raise this, in case anyone had some ideas as to what would cause this, and whether it's something that could be fixed up somehow.

The Geometries are read in using: `foreach (var feature in Shapefile.ReadAllFeatures(filePath)){ ... }`

The Shapefile I used for this example:
[Example Shape file.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/files/10967594/Example.Shape.file.zip)

Apologies if this isn't an issue,
Thanks in advance,

Emma

**Comment by KubaSzostak** [comment]
Hi @Em3a-c, more explanation will be needed here. I suppose, you are reading the Shapefile and then you are creating geometries for Bing Maps control, right? Can you provide the code that generates those geometries?

I checked the Shapefile with PostGIS and everything seems to be fine.
```cs
var geoms = features.Select(f => $"'{f.Geometry.ToText()}'::geometry \r\n");
var sql = "SELECT " + string.Join("UNION ALL SELECT ", geoms);
```
![image](https://user-images.githubusercontent.com/4609437/226174760-64cbfbe0-ac59-43f9-b118-312a3e9d3e3f.png)

**Comment by Em3a-c** [comment]
Hi @KubaSzostak,

The shapefiles are being read in with:

```
public IEnumerable<Geometry> GetShapeFileGeometries(string filePath)
{
    var geometries = new List<Geometry>();

    var opts = new ShapefileReaderOptions()
    {
        GeometryBuilderMode = GeometryBuilderMode.IgnoreInvalidShapes
    };

    foreach (var feature in Shapefile.ReadAllFeatures(filePath, opts))
    {
        if (feature.Geometry.IsValid)
        {
            geometries.Add(feature.Geometry);
        }
    }
    return geometries;
}
```

The geometries are used to create a collection of Microsoft.Maps.MapControl.WPF.MapShapeBase objects. I suspect that the logic here is not correct..
I've not included point/polyline creation, as these 'seem' to render ok. 

```
class MapPolygonShapesFactory
{
    public IEnumerable<MapShapeBase> BuildShapes(IEnumerable<NetTopologySuite.Geometries.Geometry> geometries)
    {
        var mapShapes = new List<Microsoft.Maps.MapControl.WPF.MapShapeBase>();

        foreach (var geometry in geometries)
        {
            NetTopologySuite.Geometries.GeometryFactory factory = geometry.Factory;
            NetTopologySuite.Geometries.Coordinate[] coordinates = geometry.Coordinates;
            NetTopologySuite.Geometries.Point[] points = coordinates.Select(factory.CreatePoint).ToArray();

            if (points.Count() < 1) continue;

            var mapPolygon = new MapPolygon
            {
                Locations = CreateLocationCollection(points),
                Stroke = new SolidColorBrush(Colors.Black),
                Fill = new SolidColorBrush(Colors.Orange),
                StrokeThickness = 2
            };
            mapShapes.Add(mapPolygon);
        }

        return mapShapes.ToArray();
    }

    private LocationCollection CreateLocationCollection(Point[] points)
    {
        var locations = new LocationCollection();
        foreach (var point in points)
        {
            // For the Location construction, pass in point.Y for latitude and point.X for longitude.
            locations.Add(new Microsoft.Maps.MapControl.WPF.Location(point.Y, point.X));
        }
        return locations;
    }
}
```

This bit is probably not that important, but the collection of Microsoft.Maps.MapControl.WPF.MapShapeBase are then added to a Microsoft.Maps.MapControl.WPF.MapLayer in a viewmodel, i.e

```
public void AddShapesToMap(IEnumerable<MapShapeBase> shapes)
{
     var mapLayer = new MapLayer();
 
     foreach(var shape in shapes)
     {
         mapLayer.Children.Add(shape);
     }
     MapLayers.Add(mapLayer);
     MapLayers = new []{mapLayer};  // Only allow one map layer in this code snippet.
}

public MapLayer[] MapLayers{ get; set; } 
```

The Microsoft.Maps.MapControl.WPF.MapLayer is then bound to the Microsoft.Maps.MapControl.WPF.MapItemsControl in the view (xaml).
```
<m:Map ...>
    <m:MapItemsControl ItemsSource="{Binding Path=MapLayers}"/>
</m:Map>
```

I suspect the problem is how I'm creating the MapShapeBase objects from the geometry coordinates..

Thanks alot for your help,

Emma

**Comment by FObermaier** [comment]
For `MultiPolygon`s and/or `Polygon`s with interior holes your transformation is not correct. You must not use all `Coordinates` of those geometries to build a `MapShape`  but use each component's `Coordinates` by itself:

```C#
public IEnumerable<MapShapeBase> BuildShapes(IEnumerable<NetTopologySuite.Geometries.Geometry> geometries)
{
    var mapShapes = new List<Microsoft.Maps.MapControl.WPF.MapShapeBase>();

    foreach (var geometry in geometries)
    {
        for (int i = 0; i < geometry.NumGeometries; i++) {
            var itm = geometry.GetGeometryN(i);
            if (!(itm is Polygon polygon)) continue;
            NetTopologySuite.Geometries.GeometryFactory factory = polygon.Factory;
            
            // outer shell
            NetTopologySuite.Geometries.Coordinate[] coordinates = polygon.ExteriorRing.Coordinates;
            /* transform steps for outer shell of wpf map polygon*/
            
            for (int j = 0; j < polygon.NumInteriorRings; j++) {
                coordinates = polygon.GetInteriorRingN(j).Coordinates;
                /* transform steps for inner hole of wpf map polygon*/
            }
            // build map polygon
            var mapPolygon = /* sth. */
            mapShapes.Add(mapPolygon);
        }
    }

    return mapShapes.ToArray();
}
```

**Comment by Em3a-c** [comment]
I'll have to do some reading around ExteriorRing & GetInteriorRingN property/method, and try to get a working solution. Thanks for your suggestions @FObermaier

**Comment by KubaSzostak** [comment]
Hi @Em3a-c, do you need more support on this issue? If so, provide further details, please.

**Comment by Em3a-c** [comment]
Hi @KubaSzostak,

I haven't yet managed to get this working, having tried using the suggestion above from @FObermaier,
If no one else can reproduce this issue, then maybe it's worth closing this issue for now, and when I next get a chance, I'll look at this again, and see if I can get a working solution.

Thanks
