### ISSUE TITLE
Merge https://github.com/FObermaier/SharpSbn

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite.IO.Esri#28]
Is there interest to provide support for Shapfile's spatial index (SBN) with this package?

**Comment by KubaSzostak** [comment]
Not from my side. I use things like [IndexedPointInAreaLocator](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Algorithm/Locate/IndexedPointInAreaLocator.cs) for spatial indexing.
