### ISSUE TITLE
PointZ shapefiles are not properly read

### ISSUE THREAD

**Issue by ShinNoNoir** [NetTopologySuite/NetTopologySuite.IO.Esri#29]
When reading a PointZ shapefile ([example file](https://www.arcgis.com/home/item.html?id=1f87126514a24dd697f3a70ef64e9f62)), the Z coordinates of the Point geometries remain NaN.

**Comment by KubaSzostak** [comment]
Hi @ShinNoNoir, I checked the layer you provided. It has a geometry of type `Point`, not `PointZM`. In that case if you try to read Z  coordinate from geometry then you get NaN. There is a valid Z value, but it's not a coordinate, but an attribute.

That's how it looks in QGIS:
![image](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/assets/4609437/2a47ec7e-1f5b-46dd-92de-020bd5c700c4)

You can read the same data using C# code:
```cs
var features = Shapefile.ReadAllFeatures("2021_Paspunten_BM5.shp");
foreach (var feature in features)
{
    Console.WriteLine($"Geometry: {feature.Geometry}");
    Console.WriteLine($"XYMZ: {feature.Geometry.Coordinate.X} {feature.Geometry.Coordinate.Y} {feature.Geometry.Coordinate.M} {feature.Geometry.Coordinate.Z}");
                Console.WriteLine("Attributes:");
    foreach( var name in feature.Attributes.GetNames())
    {
        var value = feature.Attributes[name];
        Console.WriteLine($"  {name}: {value}");
    }
    Console.WriteLine();
}
```

Output:
```console
Geometry: POINT (172354.84 534578.751)
XYMZ: 172354.84 534578.751 NaN NaN
Attributes:
  Puntnummer: 580_1010
  X: 172354.84
  Y: 534578.751
  Z: -3.055
  Bron: 2021_paspuntcoordinaten_05_80_hrl
  POINT_X: 
  POINT_Y: 

...
```

I hope this explanation solves your issue. If you need more support on this issue provide further details, please.

**Comment by ShinNoNoir** [comment]
Thank you for your time. This explains the issue I was having back then.
