### ISSUE TITLE
Is there a way to get shapefile field aliases?

### ISSUE THREAD

**Issue by mburbea** [NetTopologySuite/NetTopologySuite.IO.Esri#30]
Dbf has a limit of 10 characters in fieldnames, but when I view some shapefiles in arcgis pro, I can see the real field name like `RECORDED_1` and then an Alias for the field like `Recorded department`

I would like to be able to view the aliases.

**Comment by KubaSzostak** [comment]
Hi @mburbea, at first glance it seems to me like filed alias is stored in ArcGIS Pro project, not in the DBF file. Can you create a new ArcGIS project and open the same DBF file? If there is an alias name then provide us a sample file having such alias. I will take a look on it.

**Comment by KubaSzostak** [comment]
We have requested more information regarding this issue, but have not received a response or additional information regarding this issue. Therefore, we are closing this issue. Please feel free to reopen it if you are able to provide the necessary details.
