### ISSUE TITLE
Problem with saving attributes readed from existing file

### ISSUE THREAD

**Issue by Maggus85** [NetTopologySuite/NetTopologySuite.IO.Esri#33]
I'm trying to save shape file after reading it, but I receive exception

System.NotSupportedException: Unsupported dBASE field type: RuntimeType (System.Object)

From my investigation it looks like that problem is when field has null value

Sample code and shp file used to generate error attached
[sample.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/files/12062433/sample.zip)

**Comment by KubaSzostak** [comment]
Related to #31.
