### ISSUE TITLE
nuget out of date

### ISSUE THREAD

**Issue by MattPil29** [NetTopologySuite/NetTopologySuite.IO.Esri#35]
Hi,

Thanks for the great project.  The latest fixes to help skip invalid geometry and cope with poor dates are really useful.  Can I ask that you publish a fresh nuget so we can refrence it (much nicer than copying your code locally).

Thanks again, Matt

**Comment by mburbea** [comment]
+1, it's quite annoying having to keep this library as a source reference just because some vendor likes to send `00000000` dates

**Comment by valttlapp** [comment]
+1, would like to have that new stream support also available from nuget package!

**Comment by mahdirastegari** [comment]
I am interested in having another release or even a beta release to be able to use the package.

**Comment by KubaSzostak** [comment]
Hi @FObermaier, 
from my point of view, all important issues have been resolved, and I think we're ready to proceed with publishing the new version of the NuGet package.

Additionally, I would suggest considering marking the previous NuGet package, NetTopologySuite.IO.ShapeFile, as [deprecated](https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages). It hasn't been updated in more than two years. Therefore, I believe that encouraging our users to move to the new, actively maintained NetTopologySuite.IO.Esri package would be beneficial for the community.

**Comment by FObermaier** [comment]
Released v1.1
* https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/releases/tag/v1.1
* https://www.nuget.org/packages/NetTopologySuite.IO.ShapeFile/
