### ISSUE TITLE
Issue with 'L' Column in DBF with Length greater than 1.

### ISSUE THREAD

**Issue by mahdirastegari** [NetTopologySuite/NetTopologySuite.IO.Esri#51]
I encountered a shapefile with an 'L' column where the Length is greater than 1. However, when reading the logical column, You will encounter an exception as the position of the reading stream is mismatched.
![image](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/assets/8531566/25a6926a-4257-4861-b806-e369e89d9b8d)

Here is the shape file zipped which I face the issue.
[roads4.zip](https://github.com/user-attachments/files/16065190/roads4.zip)

Although I understand that the Logic column should have a Length of 1, other importers such as QGIS can import this file correctly, so I believe we should address the issue.

**Comment by KubaSzostak** [comment]
Fixed by #52. Thank you @mahdirastegari.
