### ISSUE TITLE
NetTopologySuite.IO.Esri.ShapefileException:“Invalid polygon geometry.”

### ISSUE THREAD

**Issue by xiabin68** [NetTopologySuite/NetTopologySuite.IO.Esri#55]
List<Feature> kcdjfer = new List<Feature>();
var fk = Shapefile.OpenRead(shpPath);
foreach(var fere in fk)
{
kcdjfer.Add(fere);
}

here    (var fere in fk)    NetTopologySuite.IO.Esri.ShapefileException:“Invalid polygon geometry.”

![ERRE](https://github.com/user-attachments/assets/b9ae9e8b-254d-457c-91e2-dff74db1d8b1)

**Comment by KubaSzostak** [comment]
This error typically occurs when the geometry in the shapefile does not meet the OGC standards, which might include issues like self-intersecting polygons or incorrectly ordered vertices. To handle this issue, you can use the `GeometryBuilderMode.FixInvalidShapes` option which attempts to automatically correct some of the common geometry errors when reading shapefiles. 
 
```cs
var options = new ShapefileReaderOptions
{
    GeometryBuilderMode = GeometryBuilderMode.FixInvalidShapes
};

var kcdjfer = new List<Feature>();
using var fk = Shapefile.OpenRead(shpPath, options);
foreach (var fere in fk)
{
    kcdjfer.Add(fere);
}
```

If this does not resolve the issue, please share the problematic shapefile, or a part of it containing the error, for a more detailed diagnosis.

**Comment by xiabin68** [comment]
这是来自QQ邮箱的自动回复邮件。
 
    您好，你发送的邮件我已经收到。。

**Comment by xiabin68** [comment]
Thank you very much for your reply. Now I will try using your method to see if this problem can be solved

**Comment by KubaSzostak** [comment]
I hope the solution I provided helped resolve the issue. As there hasn't been any follow-up, I'm closing this issue for now. If the problem persists or if you have any further questions, feel free to reopen the issue or create a new one.
