### ISSUE TITLE
Add Test project from NetTopologySuite.IO.ShapeFile repository

### ISSUE THREAD

**Issue by KubaSzostak** [NetTopologySuite/NetTopologySuite.IO.Esri#8]
I have added  [tests from NetTopologySuite.IO.ShapeFile repository](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/pull/7). Can someone take a look on it, please?

**Comment by FObermaier** [comment]
Closed with f948075426fcdf370ad1c7509d6b8bd326f60eb7
